define([
	"jquery",
	"jquery.bootstrap",
	"jquery.ui",
	"jquery.ui.touch-punch",
	"jquery.ui.custom",
	"underscore",
	"backbone",
	"backbone.marionette",
	"backbone.localStorage",
	"backbone.validation",
	"moment",
	"jquery.qrcode",
	"text",
], function() { });